/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cart/items/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update item quantity
         * @description Updates the quantity of an item in the cart
         */
        put: operations["updateItemQuantity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders
         * @description Retrieves a list of all orders
         */
        get: operations["listOrders"];
        put?: never;
        /**
         * Create order
         * @description Creates a new order from the provided order details
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add item to cart
         * @description Adds a product to the shopping cart or updates quantity if already exists
         */
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get paginated products
         * @description Retrieves a paginated list of products from the catalog
         */
        get: operations["getProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get product by code
         * @description Retrieves a specific product by its unique code
         */
        get: operations["getProductByCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order details
         * @description Retrieves detailed information about a specific order
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cart
         * @description Retrieves the current shopping cart contents
         */
        get: operations["getCart"];
        put?: never;
        post?: never;
        /**
         * Clear cart
         * @description Removes all items from the shopping cart
         */
        delete: operations["clearCart"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request to update cart item quantity */
        UpdateQuantityRequest: {
            /**
             * Format: int32
             * @description New quantity
             * @example 3
             */
            quantity: number;
        };
        /** @description Shopping cart with items and total */
        CartDto: {
            /** @description Cart items */
            items: components["schemas"]["CartItemDto"][];
            /**
             * @description Total amount
             * @example 99.99
             */
            totalAmount?: number;
            /**
             * Format: int32
             * @description Number of items in cart
             * @example 3
             */
            itemCount?: number;
        };
        /** @description Shopping cart line item */
        CartItemDto: {
            /**
             * @description Product code
             * @example P001
             */
            code?: string;
            /**
             * @description Product name
             * @example Spring Boot in Action
             */
            name?: string;
            /**
             * @description Unit price
             * @example 29.99
             */
            price?: number;
            /**
             * Format: int32
             * @description Quantity
             * @example 2
             */
            quantity?: number;
            /**
             * @description Subtotal (price * quantity)
             * @example 59.98
             */
            subtotal?: number;
        };
        /** @description Request to create a new order */
        CreateOrderRequest: {
            customer: components["schemas"]["Customer"];
            /**
             * @description Delivery address
             * @example 742 Evergreen Terrace, Springfield
             */
            deliveryAddress: string;
            item: components["schemas"]["OrderItem"];
        };
        /** @description Customer information for order */
        Customer: {
            /**
             * @description Customer full name
             * @example John Doe
             */
            name: string;
            /**
             * @description Customer email address
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Customer phone number
             * @example +1-555-123-4567
             */
            phone: string;
        };
        /** @description Order line item representing a product in the order */
        OrderItem: {
            /**
             * @description Product code
             * @example P100
             */
            code: string;
            /**
             * @description Product name
             * @example The Hunger Games
             */
            name: string;
            /**
             * @description Product price
             * @example 34
             */
            price: number;
            /**
             * Format: int32
             * @description Order quantity
             * @example 2
             */
            quantity: number;
        };
        /** @description Response after creating an order */
        CreateOrderResponse: {
            /**
             * @description Unique order number
             * @example ORD-2025-001234
             */
            orderNumber: string;
        };
        /** @description Request to add item to cart */
        AddToCartRequest: {
            /**
             * @description Product code
             * @example P001
             */
            code: string;
            /**
             * Format: int32
             * @description Quantity to add
             * @example 1
             */
            quantity: number;
        };
        /** @description Paginated response containing data and pagination metadata */
        PagedResult: {
            /** @description List of items for the current page */
            data: Record<string, never>[];
            /**
             * Format: int64
             * @description Total number of elements across all pages
             * @example 100
             */
            totalElements: number;
            /**
             * Format: int32
             * @description Current page number (1-based)
             * @example 1
             */
            pageNumber: number;
            /**
             * Format: int32
             * @description Total number of pages
             * @example 10
             */
            totalPages: number;
            /**
             * @description Whether this is the first page
             * @example true
             */
            isFirst: boolean;
            /**
             * @description Whether this is the last page
             * @example false
             */
            isLast: boolean;
            /**
             * @description Whether there is a next page available
             * @example true
             */
            hasNext: boolean;
            /**
             * @description Whether there is a previous page available
             * @example false
             */
            hasPrevious: boolean;
        };
        /** @description Product information */
        ProductDto: {
            /**
             * @description Unique product code
             * @example P100
             */
            code: string;
            /**
             * @description Product name
             * @example The Hunger Games
             */
            name: string;
            /**
             * @description Product description
             * @example Winning will make you famous. Losing means certain death...
             */
            description?: string;
            /**
             * @description Product image URL
             * @example https://images.sivalabs.in/products/the-hunger-games.jpg
             */
            imageUrl?: string;
            /**
             * @description Product price
             * @example 34
             */
            price: number;
        };
        /** @description Summary view of an order */
        OrderView: {
            /**
             * @description Unique order number
             * @example ORD-2025-001234
             */
            orderNumber: string;
            /**
             * @description Order status
             * @example NEW
             * @enum {string}
             */
            status: "NEW" | "IN_PROCESS" | "DELIVERED" | "CANCELLED" | "ERROR";
            customer: components["schemas"]["Customer"];
        };
        /** @description Complete order details */
        OrderDto: {
            /**
             * @description Unique order number
             * @example ORD-2025-001234
             */
            orderNumber: string;
            item: components["schemas"]["OrderItem"];
            customer: components["schemas"]["Customer"];
            /**
             * @description Delivery address
             * @example 742 Evergreen Terrace, Springfield
             */
            deliveryAddress: string;
            /**
             * @description Order status
             * @example NEW
             * @enum {string}
             */
            status: "NEW" | "IN_PROCESS" | "DELIVERED" | "CANCELLED" | "ERROR";
            /**
             * Format: date-time
             * @description Order creation timestamp
             */
            createdAt: string;
            /**
             * @description Total order amount (price × quantity)
             * @example 68
             */
            readonly totalAmount?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateItemQuantity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuantityRequest"];
            };
        };
        responses: {
            /** @description Item quantity updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartDto"];
                };
            };
            /** @description Invalid quantity */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartDto"];
                };
            };
            /** @description Item not found in cart */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartDto"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderView"];
                };
            };
            /** @description Orders service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderView"][];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateOrderResponse"];
                };
            };
            /** @description Invalid order data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateOrderResponse"];
                };
            };
            /** @description Orders service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateOrderResponse"];
                };
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToCartRequest"];
            };
        };
        responses: {
            /** @description Item added to cart successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartDto"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartDto"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartDto"];
                };
            };
        };
    };
    getProducts: {
        parameters: {
            query?: {
                /**
                 * @description Page number (1-based)
                 * @example 1
                 */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved product list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResult"];
                };
            };
        };
    };
    getProductByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Product code
                 * @example P100
                 */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductDto"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderDto"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderDto"];
                };
            };
            /** @description Orders service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderDto"];
                };
            };
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartDto"];
                };
            };
        };
    };
    clearCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart cleared successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
