/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get paginated list of books
         * @description Retrieve books from catalog with pagination support
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-indexed) */
                    page?: number;
                    /** @description Number of items per page */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Books retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookListResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current shopping cart
         * @description Retrieve current cart contents
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cart retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                /** @description Cart not found (empty cart) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add book to cart
         * @description Add a book to the shopping cart (replaces existing item in simplified model)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddToCartRequest"];
                };
            };
            responses: {
                /** @description Book added to cart successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                /** @description Invalid book code or request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update cart item quantity
         * @description Update the quantity of an item in the cart
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCartRequest"];
                };
            };
            responses: {
                /** @description Cart updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                /** @description Invalid quantity or book code */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cart not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all orders
         * @description Get list of all orders with basic information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Orders retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderListResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create new order
         * @description Place a new order with customer information and delivery address
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrderFormData"];
                };
            };
            responses: {
                /** @description Order created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                /** @description Validation error or invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order details
         * @description Retrieve detailed information for a specific order
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique order identifier */
                    orderNumber: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order details retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderDetailResponse"];
                    };
                };
                /** @description Order not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Book: {
            /**
             * @description Unique book identifier
             * @example book-001
             */
            code: string;
            /**
             * @description Full book title
             * @example The Great Gatsby
             */
            name: string;
            /**
             * @description Author name
             * @example F. Scott Fitzgerald
             */
            author: string;
            /**
             * @description Price in USD
             * @example 19.99
             */
            price: number;
            /**
             * Format: uri
             * @description URL to book cover image
             * @example https://example.com/covers/great-gatsby.jpg
             */
            imageUrl: string;
        };
        CartItem: {
            /**
             * @description Book code reference
             * @example book-001
             */
            code: string;
            /**
             * @description Book name (snapshot)
             * @example The Great Gatsby
             */
            name: string;
            /**
             * @description Unit price (snapshot)
             * @example 19.99
             */
            price: number;
            /**
             * @description Quantity in cart
             * @example 2
             */
            quantity: number;
        };
        Cart: {
            /** @description Single cart item (simplified model) */
            item?: components["schemas"]["CartItem"] & unknown;
            /**
             * @description Calculated total amount
             * @example 39.98
             */
            totalAmount: number;
        };
        Customer: {
            /**
             * @description Customer full name
             * @example John Doe
             */
            name: string;
            /**
             * Format: email
             * @description Customer email address
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Customer phone number
             * @example +1-555-123-4567
             */
            phone: string;
        };
        Order: {
            /**
             * @description Unique order identifier
             * @example ORD-20251011-001
             */
            orderNumber: string;
            /**
             * @description Current order status
             * @example NEW
             * @enum {string}
             */
            status: "NEW" | "CONFIRMED" | "PROCESSING" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            customer: components["schemas"]["Customer"];
            /**
             * @description Full delivery address
             * @example 123 Main St, Anytown, ST 12345, USA
             */
            deliveryAddress: string;
            /** @description Ordered items (snapshot) */
            items: components["schemas"]["CartItem"][];
            /**
             * @description Total order amount
             * @example 39.98
             */
            totalAmount: number;
            /**
             * Format: date-time
             * @description Order creation timestamp
             * @example 2025-10-11T10:30:00Z
             */
            createdAt: string;
        };
        AddToCartRequest: {
            /**
             * @description Book code to add to cart
             * @example book-001
             */
            code: string;
        };
        UpdateCartRequest: {
            /**
             * @description Book code to update
             * @example book-001
             */
            code: string;
            /**
             * @description New quantity
             * @example 3
             */
            quantity: number;
        };
        OrderFormData: {
            customer: components["schemas"]["Customer"];
            /**
             * @description Complete delivery address
             * @example 123 Main St, Anytown, ST 12345, USA
             */
            deliveryAddress: string;
        };
        BookListResponse: {
            /** @description Array of books for current page */
            data: components["schemas"]["Book"][];
            pagination: {
                /**
                 * @description Current page number (1-indexed)
                 * @example 1
                 */
                page: number;
                /**
                 * @description Items per page
                 * @example 10
                 */
                pageSize: number;
                /**
                 * @description Total number of pages
                 * @example 5
                 */
                totalPages: number;
                /**
                 * @description Total books in catalog
                 * @example 42
                 */
                totalItems: number;
            };
        };
        OrderListResponse: {
            orders: {
                /** @example ORD-20251011-001 */
                orderNumber: string;
                /**
                 * @example NEW
                 * @enum {string}
                 */
                status: "NEW" | "CONFIRMED" | "PROCESSING" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            }[];
        };
        OrderDetailResponse: {
            order: components["schemas"]["Order"];
        };
        ErrorResponse: {
            /**
             * @description Error type identifier
             * @example VALIDATION_ERROR
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Invalid email format
             */
            message: string;
            /**
             * @description Additional error details
             * @example {
             *       "field": "customer.email",
             *       "code": "INVALID_FORMAT"
             *     }
             */
            details?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
