/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated list of books */
        get: operations["listBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current shopping cart */
        get: operations["getCart"];
        put?: never;
        /** Add book to cart */
        post: operations["addToCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update cart item quantity */
        post: operations["updateCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of all orders */
        get: operations["listOrders"];
        put?: never;
        /** Create new order */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order details by order number */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Book: {
            /**
             * @description Unique book identifier
             * @example book-001
             */
            code: string;
            /**
             * @description Full book title
             * @example A Game of Thrones
             */
            name: string;
            /**
             * @description Author name
             * @example George R.R. Martin
             */
            author: string;
            /**
             * Format: float
             * @description Price in USD
             * @example 19.2
             */
            price: number;
            /**
             * Format: uri
             * @description URL to book cover image
             * @example /images/books/game-of-thrones.jpg
             */
            imageUrl: string;
        };
        Pagination: {
            /** @description Current page number (1-indexed) */
            page: number;
            /** @description Items per page */
            pageSize: number;
            /** @description Total number of pages */
            totalPages: number;
            /** @description Total number of items in catalog */
            totalItems: number;
        };
        BookListResponse: {
            /** @description Array of books for current page */
            data: components["schemas"]["Book"][];
            pagination: components["schemas"]["Pagination"];
        };
        CartItem: {
            /**
             * @description Book code
             * @example book-001
             */
            code: string;
            /**
             * @description Book name
             * @example A Game of Thrones
             */
            name: string;
            /**
             * Format: float
             * @description Unit price in USD
             * @example 19.2
             */
            price: number;
            /**
             * @description Quantity in cart
             * @example 2
             */
            quantity: number;
        };
        Cart: {
            /** @description Single cart item (null if cart is empty) */
            item?: components["schemas"]["CartItem"] | null;
            /**
             * Format: float
             * @description Total amount (price × quantity)
             * @example 38.4
             */
            totalAmount: number;
        };
        AddToCartRequest: {
            /**
             * @description Book code to add to cart
             * @example book-001
             */
            code: string;
        };
        UpdateCartRequest: {
            /**
             * @description Book code
             * @example book-001
             */
            code: string;
            /**
             * @description New quantity
             * @example 3
             */
            quantity: number;
        };
        Customer: {
            /**
             * @description Customer name
             * @example John Doe
             */
            name: string;
            /**
             * Format: email
             * @description Customer email address
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Customer phone number
             * @example +1-555-0123
             */
            phone: string;
        };
        OrderFormData: {
            customer: components["schemas"]["Customer"];
            /**
             * @description Full delivery address
             * @example 123 Main St, Apt 4B, New York, NY 10001
             */
            deliveryAddress: string;
        };
        Order: {
            /**
             * @description Unique order identifier
             * @example ORD-20250110-001
             */
            orderNumber: string;
            /**
             * @description Order status
             * @example NEW
             * @enum {string}
             */
            status: "NEW" | "CONFIRMED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
            customer: components["schemas"]["Customer"];
            /** @description Delivery address */
            deliveryAddress: string;
            /** @description Ordered items */
            items: components["schemas"]["CartItem"][];
            /**
             * Format: float
             * @description Total order amount in USD
             */
            totalAmount: number;
            /**
             * Format: date-time
             * @description Order creation timestamp (ISO 8601)
             * @example 2025-01-10T14:30:00Z
             */
            createdAt: string;
        };
        OrderSummary: {
            /**
             * @description Order number
             * @example ORD-20250110-001
             */
            orderNumber: string;
            /**
             * @description Order status
             * @example NEW
             * @enum {string}
             */
            status: "NEW" | "CONFIRMED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
        };
        OrderListResponse: {
            /** @description List of order summaries */
            orders: components["schemas"]["OrderSummary"][];
        };
        OrderDetailResponse: {
            order: components["schemas"]["Order"];
        };
        Error: {
            /**
             * @description Error message
             * @example Book not found
             */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBooks: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Number of items per page */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with paginated book list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookListResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current cart contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            /** @description Cart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addToCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToCartRequest"];
            };
        };
        responses: {
            /** @description Book added to cart successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            /** @description Invalid book code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartRequest"];
            };
        };
        responses: {
            /** @description Cart updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            /** @description Invalid quantity */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Cart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderFormData"];
            };
        };
        responses: {
            /** @description Order created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order number (e.g., ORD-20250110-001) */
                orderNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailResponse"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
